# Generated by Django 6.0.3 on 2026-04-06 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_core', '0003_legacynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='relationship',
            field=models.CharField(choices=[('spouse', 'Spouse / Partner'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('business', 'Business Partner'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='threshold_days',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='legacynote',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, related_name='assigned_notes', to='legacy_core.beneficiary'),
        ),
        migrations.AddField(
            model_name='legacynote',
            name='category',
            field=models.CharField(choices=[('social', 'Social Media'), ('finance', 'Finance / Banking'), ('crypto', 'Crypto / NFTs'), ('email', 'Email Accounts'), ('devices', 'Devices / Passwords'), ('message', 'Personal Message'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
