# Generated by Django 6.0.3 on 2026-04-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_core', '0004_beneficiary_created_at_beneficiary_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacynote',
            name='decryption_hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
