# Generated by Django 4.2 on 2026-05-06 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_core', '0006_customuser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='vault/%Y/%m/')),
                ('file_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiaries', models.ManyToManyField(blank=True, related_name='assigned_assets', to='legacy_core.beneficiary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
