# Generated by Django 4.2 on 2026-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_core', '0007_legacyasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('crypto_salt', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='legacyasset',
            name='file_extension',
        ),
        migrations.RemoveField(
            model_name='legacyasset',
            name='file_size',
        ),
        migrations.AddField(
            model_name='legacyasset',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
