# Generated by Django 4.2 on 2026-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_core', '0009_customuser_address_customuser_bio_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyasset',
            name='encrypted_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacyasset',
            name='file_size_kb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacyasset',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legacyasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vault/%Y/%m/'),
        ),
    ]
